name: Test-E2E

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          cache: npm
          node-version: '20.5.1'
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
      - run: |
          npm ci
          npm run build

      - name: E2E Tests
        run: npx lerna run test-e2e

      - name: Synthetix CI Downstream
        run: npx lerna run test-snx-ci
